#!/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "You have to run this script as root."
       echo "Try 'sudo ./install_root'!"
       echo "If you don't have root access try running './install'."
  exit -1
fi

USER_HOME=$(eval echo ~${SUDO_USER})

hash git 2>/dev/null || { echo >&2 "Make sure, that 'git' is installed. Aborting."; exit 1; }

# symlinks
## tmux
ln -s -f $USER_HOME/dotfiles/tmux.conf $USER_HOME/.tmux.conf
## bash
ln -s -f $USER_HOME/dotfiles/bash_profile $USER_HOME/.bash_profile
ln -s -f $USER_HOME/dotfiles/bashrc $USER_HOME/.bashrc
## vim
ln -s -f $USER_HOME/dotfiles/vimrc $USER_HOME/.vimrc
ln -s -f $USER_HOME/dotfiles/gvimrc $USER_HOME/.gvimrc
ln -s -f $USER_HOME/dotfiles/vimrc.bundles $USER_HOME/.vimrc.bundles
ln -s -f $USER_HOME/dotfiles/vim $USER_HOME/
mv -T $USER_HOME/vim $USER_HOME/.vim

# root symlinks
## tmux
ln -s -f $USER_HOME/.tmux.conf /root/.tmux.conf
## bash
ln -s -f $USER_HOME/.bash_profile /root/.bash_profile
ln -s -f $USER_HOME/.bashrc /root/.bashrc
## vim
ln -s -f $USER_HOME/.vim/ /root/
ln -s -f $USER_HOME/.vimrc /root/.vimrc
ln -s -f $USER_HOME/.gvimrc /root/.gvimrc
ln -s -f $USER_HOME/.vimrc.bundles /root/.vimrc.bundles

echo "Symlinks successfully created for ~/dotfiles."

# Install fonts
if ! fc-list | grep -i Sauce\ Code\ Powerline\ Regular.otf >/dev/null; then
    git clone https://github.com/powerline/fonts.git /root/fonts
    sh /root/fonts/install.sh
    echo "Set your terminal font to 'Source Code Pro'."
    rm -rf /root/fonts
fi

exit 0
