#!/bin/bash

hash git 2>/dev/null || { echo >&2 "Make sure, that 'git' is installed. Aborting."; exit 1; }

# symlinks
## tmux
ln -s -f $HOME/dotfiles/tmux.conf $HOME/.tmux.conf
git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
## bash
ln -s -f $HOME/dotfiles/zprofile $HOME/.zprofile
ln -s -f $HOME/dotfiles/zshrc $HOME/.zshrc
## vim
ln -s -f $HOME/dotfiles/vimrc $HOME/.vimrc
ln -s -f $HOME/dotfiles/gvimrc $HOME/.gvimrc
ln -s -f $HOME/dotfiles/vimrc.bundles $HOME/.vimrc.bundles
ln -s -f $HOME/dotfiles/vim $HOME/
mv -T $HOME/vim $HOME/.vim

echo "Symlinks successfully created for ~/dotfiles."

# Install fonts
if ! fc-list | grep -i Sauce\ Code\ Powerline\ Regular.otf >/dev/null; then
    git clone https://github.com/powerline/fonts.git $HOME/fonts
    sh $HOME/fonts/install.sh
    echo "Set your terminal font to 'Source Code Pro'."
    rm -rf $HOME/fonts
fi

exit 0
