#!/bin/bash

hash git 2>/dev/null || { echo >&2 "Make sure, that 'git' is installed. Aborting."; exit 1; }

ln -s -f $HOME/dotfiles/vimrc $HOME/.vimrc
ln -s -f $HOME/dotfiles/gvimrc $HOME/.gvimrc
ln -s -f $HOME/dotfiles/vimrc.bundles $HOME/.vimrc.bundles
ln -s -f $HOME/dotfiles/vim $HOME/
mv -T $HOME/vim $HOME/.vim

if [ ! -e $HOME/.vim/bundle/vundle ]; then
  git clone https://github.com/gmarik/vundle.git $HOME/.vim/bundle/vundle
fi
vim -u $HOME/.vimrc.bundles +BundleInstall +qa

echo "Symlinks successfully created for ~/dotfiles."

if ! fc-list | grep -i Sauce\ Code\ Powerline\ Regular.otf >/dev/null; then
    git clone https://github.com/powerline/fonts.git $HOME/fonts
    sh $HOME/fonts/install.sh
    echo "Set your terminal font to 'Source Code Pro'."
    rm -rf $HOME/fonts
fi

exit 0
