#!/bin/bash

command -v git >/dev/null 2>&1 || { echo "Make sure, that 'git' is installed. Aborting." >&2; exit 1; }

# symlinks
## alacritty
ln -s -f "$HOME/dotfiles/alacritty.toml"         "$HOME/.alacritty.toml"
## tmux
ln -s -f "$HOME/dotfiles/tmux.conf"             "$HOME/.tmux.conf"
git clone https://github.com/tmux-plugins/tpm   "$HOME/.tmux/plugins/tpm"
## zsh
ln -s -f "$HOME/dotfiles/zprofile"              "$HOME/.zprofile"
ln -s -f "$HOME/dotfiles/zshrc"                 "$HOME/.zshrc"
ln -s -f "$HOME/dotfiles/zshenv"                "$HOME/.zshenv"
## vim
mkdir -p "$HOME/.config/nvim"
ln -s -f "$HOME/dotfiles/init.lua"              "$HOME/.config/nvim/init.lua"
ln -s -f "$HOME/dotfiles/lua"                   "$HOME/.config/nvim/"
ln -s -f "$HOME/dotfiles/ftplugin"              "$HOME/.config/nvim/"
ln -s -f "$HOME/dotfiles/spell"                 "$HOME/.config/nvim/"
ln -s -f "$HOME/dotfiles/Pipfile"               "$HOME/.config/nvim/Pipfile"
## git
ln -s -f "$HOME/dotfiles/gitconfig"             "$HOME/.gitconfig"
ln -s -f "$HOME/dotfiles/gitignore"             "$HOME/.gitignore"
## spotify
mkdir -p "$HOME/.config/spotifyd"
ln -s -f "$HOME/dotfiles/spotifyd.conf"         "$HOME/.config/spotifyd/spotifyd.conf"
## gdb
ln -s -f "$HOME/dotfiles/gdbinit"               "$HOME/.gdbinit"
## ripgrep
ln -s -f "$HOME/dotfiles/ripgreprc"             "$HOME/.ripgreprc"

echo "Symlinks successfully created for ~/dotfiles."

if command -v pipenv &> /dev/null; then
    pushd "$HOME/.config/nvim" || exit 0
    pipenv install
    popd || exit 0
else
    echo "WARNING: \`pipenv\` is not installed"
    echo "To get reliable python support in nvim run"
    echo "\`pipenv install\` in \`$HOME/.config/nvim\`"
fi

mkdir -p "$HOME/.zcomp"

if command -v rustup &> /dev/null; then
    rustup completions zsh > "$HOME/.zcomp/_rustup"
    rustup completions zsh cargo > "$HOME/.zcomp/_cargo"
fi

exit 0
