#!/bin/sh

if [[ "$#" -eq 1 ]]; then
    REPO=$(basename $(git config --get remote.origin.url))
    git remote add $1 git@github.com:$1/$REPO --fetch
else
    (>&2 echo "usage: git rad <name>")
    exit 1
fi
