#!/bin/sh

# Usage:
#
# 1. Add this script to your PATH so git can find it.
# 2. Run 'git create-changelog' to create the changelog for the latest commit.
#    This will update the ChangeLog file in the top-level directory of the
#    repository.
#
# If you want to generate the ChangeLog for a specific commit run
# 'GIT_COMMIT=<hash> git create-changelog'

set -e

GIT_COMMIT=${GIT_COMMIT:-$(git rev-parse HEAD)}
today=$(date +%Y-%m-%d)
top=$(git rev-parse --show-cdup)
name=$(git log -1 --format="%an" "$GIT_COMMIT")
email=$(git log -1 --format="%ae" "$GIT_COMMIT")

output=""
output="$output$today  $name  <$email>\n\n"

git log -1 --pretty=format: --name-only "$GIT_COMMIT" | {
    deleted=$(git show --diff-filter=D --pretty=filter:% --name-only "$GIT_COMMIT")
    while read -r line; do
        case "$deleted" in
            *"$line"*)
                log="Deleted"
                ;;
            *)
                log="Likewise"
                ;;
        esac
        output="$output\t* $line: $log.\n"
    done

    { echo "$output"; cat "${top}ChangeLog"; } > "${top}ChangeLog.new"
    mv "${top}ChangeLog.new" "${top}ChangeLog"
}

